# -*- coding: utf-8 -*-
"""inclass2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F6HJ4vT5z2WOQdBgJ3ES3hbwCxQN--Uk
"""

import torch

print('test')